export const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
export const FETCH_CATS_SUCCESS = "FETCH_CATS_SUCCESS";
export const FETCH_CATS_FAILURE = "FETCH_CATS_FAILURE";
export const FETCH_CATS_PENDING = "FETCH_CATS_PENDING";